
CREATE sequence IF NOT EXISTS STAGING.seq  start = 1 increment = 1;
CREATE TABLE IF NOT EXISTS STAGING.STG_LISTING_d (
    id integer PRIMARY KEY default STAGING.seq.nextval,
    LISTING_ID NUMBER(38,0),
	LISTING_NEIGHBOURHOOD VARCHAR(100),
	PROPERTY_TYPE VARCHAR(100),
	ROOM_TYPE VARCHAR(50),
	ACCOMMODATES NUMBER(38,0),
	PRICE NUMBER(38,0),
	HAS_AVAILABILITY varchar(10),
	AVAILABILITY_30 NUMBER(38,0),
	NUMBER_OF_REVIEWS NUMBER(38,0),
	REVIEW_SCORES_RATING NUMBER(38,0),
	REVIEW_SCORES_ACCURACY NUMBER(38,0),
	REVIEW_SCORES_CLEANLINESS NUMBER(38,0),
	REVIEW_SCORES_CHECKIN NUMBER(38,0),
	REVIEW_SCORES_COMMUNICATION NUMBER(38,0),
	REVIEW_SCORES_VALUE NUMBER(38,0)	
);

CREATE sequence IF NOT EXISTS STAGING.seq1  start = 1 increment = 1;
CREATE TABLE IF NOT EXISTS STAGING.STG_HOSTING_d (
    id integer PRIMARY KEY default STAGING.seq1.nextval,
    LISTING_ID NUMBER(38,0),
	SCRAPE_ID NUMBER(38,0),
	SCRAPED_DATE VARCHAR(100),
	HOST_ID NUMBER(38,0),
	HOST_NAME VARCHAR(100),
	HOST_SINCE VARCHAR(100),
	HOST_IS_SUPERHOST VARCHAR(100),
	HOST_NEIGHBOURHOOD VARCHAR(100)
);

CREATE sequence IF NOT EXISTS STAGING.seq2  start = 1 increment = 1;
CREATE TABLE IF NOT EXISTS STAGING.STG_Census_d (
    id integer PRIMARY KEY default STAGING.seq2.nextval,
    LGA_CODE_2016 varchar(100),
	Tot_P_M NUMBER(38,0),
	Tot_P_F NUMBER(38,0),
	Tot_P_P NUMBER(38,0),
	Age_0_4_yr_M NUMBER(38,0),
	Age_0_4_yr_F NUMBER(38,0),
	Age_0_4_yr_P NUMBER(38,0),
	Age_5_14_yr_M NUMBER(38,0),
	Age_5_14_yr_F NUMBER(38,0),
	Age_5_14_yr_P NUMBER(38,0),
	Age_15_19_yr_M NUMBER(38,0),
	Age_15_19_yr_F NUMBER(38,0),
	Age_15_19_yr_P NUMBER(38,0),
	Age_20_24_yr_M NUMBER(38,0),
	Age_20_24_yr_F NUMBER(38,0),
	Age_20_24_yr_P NUMBER(38,0),
	Age_25_34_yr_M NUMBER(38,0),
	Age_25_34_yr_F NUMBER(38,0),
	Age_25_34_yr_P NUMBER(38,0),
	Age_35_44_yr_M NUMBER(38,0),
	Age_35_44_yr_F NUMBER(38,0),
	Age_35_44_yr_P NUMBER(38,0),
	Age_45_54_yr_M NUMBER(38,0),
	Age_45_54_yr_F NUMBER(38,0),
	Age_45_54_yr_P NUMBER(38,0),
	Age_55_64_yr_M NUMBER(38,0),
	Age_55_64_yr_F NUMBER(38,0),
	Age_55_64_yr_P NUMBER(38,0),
	Age_65_74_yr_M NUMBER(38,0),
	Age_65_74_yr_F NUMBER(38,0),
	Age_65_74_yr_P NUMBER(38,0),
	Age_75_84_yr_M NUMBER(38,0),
	Age_75_84_yr_F NUMBER(38,0),
	Age_75_84_yr_P NUMBER(38,0),
	Age_85ov_M NUMBER(38,0),
	Age_85ov_F NUMBER(38,0),
	Age_85ov_P NUMBER(38,0),
	Counted_Census_Night_home_M NUMBER(38,0),
	Counted_Census_Night_home_F NUMBER(38,0),
	Counted_Census_Night_home_P NUMBER(38,0),
	Count_Census_Nt_Ewhere_Aust_M NUMBER(38,0),
	Count_Census_Nt_Ewhere_Aust_F NUMBER(38,0),
	Count_Census_Nt_Ewhere_Aust_P NUMBER(38,0),
	Indigenous_Psns_Aboriginal_M NUMBER(38,0),
	Indigenous_Psns_Aboriginal_F NUMBER(38,0),
	Indigenous_Psns_Aboriginal_P NUMBER(38,0),
	Indig_Psns_Torres_Strait_Is_M NUMBER(38,0),
	Indig_Psns_Torres_Strait_Is_F NUMBER(38,0),
	Indig_Psns_Torres_Strait_Is_P NUMBER(38,0),
	Indig_Bth_Abor_Torres_St_Is_M NUMBER(38,0),
	Indig_Bth_Abor_Torres_St_Is_F NUMBER(38,0),
	Indig_Bth_Abor_Torres_St_Is_P NUMBER(38,0),
	Indigenous_P_Tot_M NUMBER(38,0),
	Indigenous_P_Tot_F NUMBER(38,0),
	Indigenous_P_Tot_P NUMBER(38,0),
	Birthplace_Australia_M NUMBER(38,0),
	Birthplace_Australia_F NUMBER(38,0),
	Birthplace_Australia_P NUMBER(38,0),
	Birthplace_Elsewhere_M NUMBER(38,0),
	Birthplace_Elsewhere_F NUMBER(38,0),
	Birthplace_Elsewhere_P NUMBER(38,0),
	Lang_spoken_home_Eng_only_M NUMBER(38,0),
	Lang_spoken_home_Eng_only_F NUMBER(38,0),
	Lang_spoken_home_Eng_only_P NUMBER(38,0),
	Lang_spoken_home_Oth_Lang_M NUMBER(38,0),
	Lang_spoken_home_Oth_Lang_F NUMBER(38,0),
	Lang_spoken_home_Oth_Lang_P NUMBER(38,0),
	Australian_citizen_M NUMBER(38,0),
	Australian_citizen_F NUMBER(38,0),
	Australian_citizen_P NUMBER(38,0),
	Age_psns_att_educ_inst_0_4_M NUMBER(38,0),
	Age_psns_att_educ_inst_0_4_F NUMBER(38,0),
	Age_psns_att_educ_inst_0_4_P NUMBER(38,0),
	Age_psns_att_educ_inst_5_14_M NUMBER(38,0),
	Age_psns_att_educ_inst_5_14_F NUMBER(38,0),
	Age_psns_att_educ_inst_5_14_P NUMBER(38,0),
	Age_psns_att_edu_inst_15_19_M NUMBER(38,0),
	Age_psns_att_edu_inst_15_19_F NUMBER(38,0),
	Age_psns_att_edu_inst_15_19_P NUMBER(38,0),
	Age_psns_att_edu_inst_20_24_M NUMBER(38,0),
	Age_psns_att_edu_inst_20_24_F NUMBER(38,0),
	Age_psns_att_edu_inst_20_24_P NUMBER(38,0),
	Age_psns_att_edu_inst_25_ov_M NUMBER(38,0),
	Age_psns_att_edu_inst_25_ov_F NUMBER(38,0),
	Age_psns_att_edu_inst_25_ov_P NUMBER(38,0),
	High_yr_schl_comp_Yr_12_eq_M NUMBER(38,0),
	High_yr_schl_comp_Yr_12_eq_F NUMBER(38,0),
	High_yr_schl_comp_Yr_12_eq_P NUMBER(38,0),
	High_yr_schl_comp_Yr_11_eq_M NUMBER(38,0),
	High_yr_schl_comp_Yr_11_eq_F NUMBER(38,0),
	High_yr_schl_comp_Yr_11_eq_P NUMBER(38,0),
	High_yr_schl_comp_Yr_10_eq_M NUMBER(38,0),
	High_yr_schl_comp_Yr_10_eq_F NUMBER(38,0),
	High_yr_schl_comp_Yr_10_eq_P NUMBER(38,0),
	High_yr_schl_comp_Yr_9_eq_M NUMBER(38,0),
	High_yr_schl_comp_Yr_9_eq_F NUMBER(38,0),
	High_yr_schl_comp_Yr_9_eq_P NUMBER(38,0),
	High_yr_schl_comp_Yr_8_belw_M NUMBER(38,0),
	High_yr_schl_comp_Yr_8_belw_F NUMBER(38,0),
	High_yr_schl_comp_Yr_8_belw_P NUMBER(38,0),
	High_yr_schl_comp_D_n_g_sch_M NUMBER(38,0),
	High_yr_schl_comp_D_n_g_sch_F NUMBER(38,0),
	High_yr_schl_comp_D_n_g_sch_P NUMBER(38,0),
	Count_Psns_occ_Priv_dwgs_M NUMBER(38,0),
	Count_Psns_occ_Priv_dwgs_F NUMBER(38,0),
	Count_Psns_occ_Priv_dwgs_P NUMBER(38,0),
	Count_Persons_other_dwgs_M NUMBER(38,0),
	Count_Persons_other_dwgs_F NUMBER(38,0),
	Count_Persons_other_dwgs_P NUMBER(38,0),
    Median_age_persons NUMBER(38,0),
	Median_mortgage_repay_monthly NUMBER(38,0),
	Median_tot_prsnl_inc_weekly NUMBER(38,0),
	Median_rent_weekly NUMBER(38,0),
	Median_tot_fam_inc_weekly NUMBER(38,0),
	Average_num_psns_per_bedroom FLOAT,
	Median_tot_hhd_inc_weekly NUMBER(38,0),
	Average_household_size FLOAT
);

CREATE sequence IF NOT EXISTS STAGING.seq4  start = 1 increment = 1;
CREATE TABLE IF NOT EXISTS STAGING.STG_SUBURB_d (
    id integer PRIMARY KEY default STAGING.seq4.nextval,
	LGA_NAME varchar(100),
	SUBURB_NAME varchar(100)
);

CREATE sequence IF NOT EXISTS STAGING.seq5  start = 1 increment = 1;
CREATE TABLE IF NOT EXISTS STAGING.STG_LGA_CODE_d (
    id integer PRIMARY KEY default STAGING.seq5.nextval,
	LGA_CODE NUMBER(38,0),
	LGA_NAME varchar(100)
);

INSERT INTO STAGING.STG_SUBURB_d(LGA_NAME,SUBURB_NAME) SELECT LGA_NAME,SUBURB_NAME FROM STAGING.NSW_LGA_SUBURB;
INSERT INTO STAGING.STG_LGA_CODE_d(LGA_CODE,LGA_NAME) SELECT * FROM STAGING.NSW_LGA_CODE;
INSERT INTO STAGING.STG_Census_d(
    LGA_CODE_2016,
	Tot_P_M,
	Tot_P_F,
	Tot_P_P,
	Age_0_4_yr_M,
	Age_0_4_yr_F,
	Age_0_4_yr_P,
	Age_5_14_yr_M,
	Age_5_14_yr_F,
	Age_5_14_yr_P,
	Age_15_19_yr_M,
	Age_15_19_yr_F,
	Age_15_19_yr_P,
	Age_20_24_yr_M,
	Age_20_24_yr_F,
	Age_20_24_yr_P,
	Age_25_34_yr_M,
	Age_25_34_yr_F,
	Age_25_34_yr_P,
	Age_35_44_yr_M,
	Age_35_44_yr_F,
	Age_35_44_yr_P,
	Age_45_54_yr_M,
	Age_45_54_yr_F,
	Age_45_54_yr_P,
	Age_55_64_yr_M,
	Age_55_64_yr_F,
	Age_55_64_yr_P,
	Age_65_74_yr_M,
	Age_65_74_yr_F,
	Age_65_74_yr_P,
	Age_75_84_yr_M,
	Age_75_84_yr_F,
	Age_75_84_yr_P,
	Age_85ov_M,
	Age_85ov_F,
	Age_85ov_P,
	Counted_Census_Night_home_M,
	Counted_Census_Night_home_F,
	Counted_Census_Night_home_P,
	Count_Census_Nt_Ewhere_Aust_M,
	Count_Census_Nt_Ewhere_Aust_F,
	Count_Census_Nt_Ewhere_Aust_P,
	Indigenous_Psns_Aboriginal_M,
	Indigenous_Psns_Aboriginal_F,
	Indigenous_Psns_Aboriginal_P,
	Indig_Psns_Torres_Strait_Is_M,
	Indig_Psns_Torres_Strait_Is_F,
	Indig_Psns_Torres_Strait_Is_P,
	Indig_Bth_Abor_Torres_St_Is_M,
	Indig_Bth_Abor_Torres_St_Is_F,
	Indig_Bth_Abor_Torres_St_Is_P,
	Indigenous_P_Tot_M,
	Indigenous_P_Tot_F,
	Indigenous_P_Tot_P,
	Birthplace_Australia_M,
	Birthplace_Australia_F,
	Birthplace_Australia_P,
	Birthplace_Elsewhere_M,
	Birthplace_Elsewhere_F,
	Birthplace_Elsewhere_P,
	Lang_spoken_home_Eng_only_M,
	Lang_spoken_home_Eng_only_F,
	Lang_spoken_home_Eng_only_P,
	Lang_spoken_home_Oth_Lang_M,
	Lang_spoken_home_Oth_Lang_F,
	Lang_spoken_home_Oth_Lang_P,
	Australian_citizen_M,
	Australian_citizen_F,
	Australian_citizen_P,
	Age_psns_att_educ_inst_0_4_M,
	Age_psns_att_educ_inst_0_4_F,
	Age_psns_att_educ_inst_0_4_P,
	Age_psns_att_educ_inst_5_14_M,
	Age_psns_att_educ_inst_5_14_F,
	Age_psns_att_educ_inst_5_14_P,
	Age_psns_att_edu_inst_15_19_M,
	Age_psns_att_edu_inst_15_19_F,
	Age_psns_att_edu_inst_15_19_P,
	Age_psns_att_edu_inst_20_24_M,
	Age_psns_att_edu_inst_20_24_F,
	Age_psns_att_edu_inst_20_24_P,
	Age_psns_att_edu_inst_25_ov_M,
	Age_psns_att_edu_inst_25_ov_F,
	Age_psns_att_edu_inst_25_ov_P,
	High_yr_schl_comp_Yr_12_eq_M,
	High_yr_schl_comp_Yr_12_eq_F,
	High_yr_schl_comp_Yr_12_eq_P,
	High_yr_schl_comp_Yr_11_eq_M,
	High_yr_schl_comp_Yr_11_eq_F,
	High_yr_schl_comp_Yr_11_eq_P,
	High_yr_schl_comp_Yr_10_eq_M,
	High_yr_schl_comp_Yr_10_eq_F,
	High_yr_schl_comp_Yr_10_eq_P,
	High_yr_schl_comp_Yr_9_eq_M,
	High_yr_schl_comp_Yr_9_eq_F,
	High_yr_schl_comp_Yr_9_eq_P,
	High_yr_schl_comp_Yr_8_belw_M,
	High_yr_schl_comp_Yr_8_belw_F,
	High_yr_schl_comp_Yr_8_belw_P,
	High_yr_schl_comp_D_n_g_sch_M,
	High_yr_schl_comp_D_n_g_sch_F,
	High_yr_schl_comp_D_n_g_sch_P,
	Count_Psns_occ_Priv_dwgs_M,
	Count_Psns_occ_Priv_dwgs_F,
	Count_Psns_occ_Priv_dwgs_P,
	Count_Persons_other_dwgs_M,
	Count_Persons_other_dwgs_F,
	Count_Persons_other_dwgs_P,
    Median_age_persons,
	Median_mortgage_repay_monthly,
	Median_tot_prsnl_inc_weekly,
	Median_rent_weekly,
	Median_tot_fam_inc_weekly,
	Average_num_psns_per_bedroom,
	Median_tot_hhd_inc_weekly,
	Average_household_size
    ) SELECT     
        RIGHT(c1."LGA_CODE_2016",5)::NUMBER(38,0) AS LGA_CODE_2016,
        c1."Tot_P_M",
        c1."Tot_P_F",
        c1."Tot_P_P",
        c1."Age_0_4_yr_M",
        c1."Age_0_4_yr_F",
        c1."Age_0_4_yr_P",
        c1."Age_5_14_yr_M",
        c1."Age_5_14_yr_F",
        c1."Age_5_14_yr_P",
        c1."Age_15_19_yr_M",
        c1."Age_15_19_yr_F",
        c1."Age_15_19_yr_P",
        c1."Age_20_24_yr_M",
        c1."Age_20_24_yr_F",
        c1."Age_20_24_yr_P",
        c1."Age_25_34_yr_M",
        c1."Age_25_34_yr_F",
        c1."Age_25_34_yr_P",
        c1."Age_35_44_yr_M",
        c1."Age_35_44_yr_F",
        c1."Age_35_44_yr_P",
        c1."Age_45_54_yr_M",
        c1."Age_45_54_yr_F",
        c1."Age_45_54_yr_P",
        c1."Age_55_64_yr_M",
        c1."Age_55_64_yr_F",
        c1."Age_55_64_yr_P",
        c1."Age_65_74_yr_M",
        c1."Age_65_74_yr_F",
        c1."Age_65_74_yr_P",
        c1."Age_75_84_yr_M",
        c1."Age_75_84_yr_F",
        c1."Age_75_84_yr_P",
        c1."Age_85ov_M",
        c1."Age_85ov_F",
        c1."Age_85ov_P",
        c1."Counted_Census_Night_home_M",
        c1."Counted_Census_Night_home_F",
        c1."Counted_Census_Night_home_P",
        c1."Count_Census_Nt_Ewhere_Aust_M",
        c1."Count_Census_Nt_Ewhere_Aust_F",
        c1."Count_Census_Nt_Ewhere_Aust_P",
        c1."Indigenous_psns_Aboriginal_M",
        c1."Indigenous_psns_Aboriginal_F",
        c1."Indigenous_psns_Aboriginal_P",
        c1."Indig_psns_Torres_Strait_Is_M",
        c1."Indig_psns_Torres_Strait_Is_F",
        c1."Indig_psns_Torres_Strait_Is_P",
        c1."Indig_Bth_Abor_Torres_St_Is_M",
        c1."Indig_Bth_Abor_Torres_St_Is_F",
        c1."Indig_Bth_Abor_Torres_St_Is_P",
        c1."Indigenous_P_Tot_M",
        c1."Indigenous_P_Tot_F",
        c1."Indigenous_P_Tot_P",
        c1."Birthplace_Australia_M",
        c1."Birthplace_Australia_F",
        c1."Birthplace_Australia_P",
        c1."Birthplace_Elsewhere_M",
        c1."Birthplace_Elsewhere_F",
        c1."Birthplace_Elsewhere_P",
        c1."Lang_spoken_home_Eng_only_M",
        c1."Lang_spoken_home_Eng_only_F",
        c1."Lang_spoken_home_Eng_only_P",
        c1."Lang_spoken_home_Oth_Lang_M",
        c1."Lang_spoken_home_Oth_Lang_F",
        c1."Lang_spoken_home_Oth_Lang_P",
        c1."Australian_citizen_M",
        c1."Australian_citizen_F",
        c1."Australian_citizen_P",
        c1."Age_psns_att_educ_inst_0_4_M",
        c1."Age_psns_att_educ_inst_0_4_F",
        c1."Age_psns_att_educ_inst_0_4_P",
        c1."Age_psns_att_educ_inst_5_14_M",
        c1."Age_psns_att_educ_inst_5_14_F",
        c1."Age_psns_att_educ_inst_5_14_P",
        c1."Age_psns_att_edu_inst_15_19_M",
        c1."Age_psns_att_edu_inst_15_19_F",
        c1."Age_psns_att_edu_inst_15_19_P",
        c1."Age_psns_att_edu_inst_20_24_M",
        c1."Age_psns_att_edu_inst_20_24_F",
        c1."Age_psns_att_edu_inst_20_24_P",
        c1."Age_psns_att_edu_inst_25_ov_M",
        c1."Age_psns_att_edu_inst_25_ov_F",
        c1."Age_psns_att_edu_inst_25_ov_P",
        c1."High_yr_schl_comp_Yr_12_eq_M",
        c1."High_yr_schl_comp_Yr_12_eq_F",
        c1."High_yr_schl_comp_Yr_12_eq_P",
        c1."High_yr_schl_comp_Yr_11_eq_M",
        c1."High_yr_schl_comp_Yr_11_eq_F",
        c1."High_yr_schl_comp_Yr_11_eq_P",
        c1."High_yr_schl_comp_Yr_10_eq_M",
        c1."High_yr_schl_comp_Yr_10_eq_F",
        c1."High_yr_schl_comp_Yr_10_eq_P",
        c1."High_yr_schl_comp_Yr_9_eq_M",
        c1."High_yr_schl_comp_Yr_9_eq_F",
        c1."High_yr_schl_comp_Yr_9_eq_P",
        c1."High_yr_schl_comp_Yr_8_belw_M",
        c1."High_yr_schl_comp_Yr_8_belw_F",
        c1."High_yr_schl_comp_Yr_8_belw_P",
        c1."High_yr_schl_comp_D_n_g_sch_M",
        c1."High_yr_schl_comp_D_n_g_sch_F",
        c1."High_yr_schl_comp_D_n_g_sch_P",
        c1."Count_psns_occ_priv_dwgs_M",
        c1."Count_psns_occ_priv_dwgs_F",
        c1."Count_psns_occ_priv_dwgs_P",
        c1."Count_Persons_other_dwgs_M",
        c1."Count_Persons_other_dwgs_F",
        c1."Count_Persons_other_dwgs_P",
        c2."Median_age_persons",
        c2."Median_mortgage_repay_monthly",
        c2."Median_tot_prsnl_inc_weekly",
        c2."Median_rent_weekly",
        c2."Median_tot_fam_inc_weekly",
        c2."Average_num_psns_per_bedroom",
        c2."Median_tot_hhd_inc_weekly",
        c2."Average_household_size" FROM STAGING.CENSUS_01 c1 INNER JOIN STAGING.CENSUS_02 c2 ON c1.lga_code_2016=c2.LGA_CODE_2016;



